### ISSUE TITLE
Questions..

### ISSUE THREAD

**Issue by bootyholebandit** [bullsei/BattleGroundEnemies#10]
Hey bullsei 

I have no idea how else i should reach out to you than here... I tried looking through your AddOn but i couldnt really find any suitable info, so i thought i would ask here instead. 

I really love the AddOn and i was hoping if there was any chance of you helping me out here.

Is it in anyway possible to use your addon as a dependency and use any of your functions in the addOn to recall the DR value of a certain unit in the battleground? E.g. the focus? I was hoping to maybe make some sort of WeakAura to help me out with CCing healers in a BG (primarily my current focus) depending on which DR it is in (immune, 1/2, etc...) 

Sorry if this is the wrong place to ask you, but i had no idea where else to reach out to you!

**Comment by bullsei** [comment]
Hi, 
i think that using a addon like diminish https://www.curseforge.com/wow/addons/diminish would probably be the best solution for that. with this addon you can also display icons similar to how BGE does it on the unitframes, player frame, focus frame etc. 
Or are you looking for something more custom that you can only achieve with a weakaura?
