### ISSUE TITLE
Persistent Options Picker Frame After 9.0.2.7-34-g67c5f9a

### ISSUE THREAD

**Issue by srhinos** [bullsei/BattleGroundEnemies#12]
Related to Target Caller (ofc)

This is persistent and rolling back to `9.0.2.7-24-g599f5df` resolves the issue

![image](https://user-images.githubusercontent.com/6531393/111244159-9af61b80-85bf-11eb-8480-f4bc4663d26c.png)

**Comment by bullsei** [comment]
fixed in alpha, release version coming soon
