### ISSUE TITLE
dispelling debuffs off of friendly targets doesnt remove them display

### ISSUE THREAD

**Issue by davidkol** [bullsei/BattleGroundEnemies#13]
whenever i dispel an ally, the debuff auras remain displaying on their bar

**Comment by bullsei** [comment]
Hi, this issue should already be fixed on the development version and will be included in the next release, i am just working on some new features that i want to include aswell

**Comment by bullsei** [comment]
Check out 9.0.5.0, Auras should be showing up completely and update correctly
