### ISSUE TITLE
Disable Arena Frames bugged for Brawl: Packed House

### ISSUE THREAD

**Issue by Xaero252** [bullsei/BattleGroundEnemies#3]
Basically, the ArenaEnemyFrame5 is showing due to what is probably just an oversight due to 5v5 no longer being a bracket.

It's a simple fix, there are 3 blocks of code to hide the default Blizzard UI; they use a for loop to iterate through and disable the default Blizzard frames for cases where BGE is used inside an "arena" All three of these blocks of code use 4 as the upper limit. Changing the 4 to a 5 disables the 5th enemy arena frame, which is currently showing during Brawl: Packed House matches.

**Comment by bullsei** [comment]
Thank you, will be fixed in next release (probably when BFA goes live) :)

**Comment by bullsei** [comment]
Fixed in latest release
