### ISSUE TITLE
Nolib

### ISSUE THREAD

**Issue by Thaodan** [bullsei/BattleGroundEnemies#4]
Can you enable nolib in pkgmeta for nolib users?

**Comment by bullsei** [comment]
Done

**Comment by Thaodan** [comment]
Thanks , just make shure that your lib is included or move the locales to the app itself.

**Comment by bullsei** [comment]
Can you confirm that the new release works as nolib as expected now?

**Comment by bullsei** [comment]
Closing this for now, seems to be fixed :D
