### ISSUE TITLE
Friendly Debuffs Not Visible

### ISSUE THREAD

**Issue by ohhelloxoxo** [bullsei/BattleGroundEnemies#7]
I'm having an issue with debuffs on friendly targets not being visible, neither in BGs nor in test mode. 

I can see debuffs on the enemies, but no matter which settings I try I'm unable to see friendly ones. I have tried disabling filtering, and enabling filtering with certain spells then testing if those debuffs were shown in a bg, no luck. 

I've tried disabling all other addons and downloading buggrabber + bugsack but nothing came up. Curious if you've heard of this issue before or have any ideas what might be causing it.

Also would like to say this is an amazing addon. thank you for all the work you put into it.  

Note: Tested with versions of BGE going back to 9.0.4-beta, no changes in behavior.

**Comment by bullsei** [comment]
Hey, thanks for the report, i will test this myself soon and let you know when i found something

**Comment by ohhelloxoxo** [comment]
Update: I was doing some more tinkering with it and after using the button to copy settings from enemies into allies, the debuffs are now visible. I tried mirroring the exact same settings in my allies frames as was in the enemies frames previously, which didn't work, but after using the copy function they are now visible.
