### ISSUE TITLE
check players in group with addon

### ISSUE THREAD

**Issue by whoizz** [bullsei/BattleGroundEnemies#9]
this is more of a feature request, would be really nice to have a button in BGE to allow us to check which players have or do not have it installed - also, never done LUA development so if there are any pointers you can provide (in terms of API on how to implement) I'd be happy to stop for a couple hours to implement and PR.

**Comment by bullsei** [comment]
Thats totally possible, i know BigWigs is having a similar function. BGE doesnt include any communication from player to player at all so i would need to look how its done and implement it. But i will definitely look it up and see how its done.

**Comment by bullsei** [comment]
Hi, so this feature is implemented in the newest alpha release now, /bgev will output the result in the chat
